### ISSUE TITLE
Add visual user feedback for token transfer through animations. 

### ISSUE THREAD

**Issue by huhn511** [machineeconomy/m2m.akitablock.io#4]
If the user sends tokens to the machine, an animation should visualize the process. 

A line connects the user wallet with the machine and a dot which "walks on the line" shows the transferring process. This animation is looped until the transfer is completed.

**Comment by huhn511** [comment]
Something like this:
![transfer_iota](https://user-images.githubusercontent.com/10562055/60283350-400f2300-9909-11e9-87f5-9b181e2113d0.gif)
Source: [https://coordicide.iota.org/module1](https://coordicide.iota.org/module1)

Todo: 
- [ ] Check how this works (looks like SVG animation)

**Comment by akitablock** [comment]
We are working on a simple and clean animation. mockups:

Order headphones and send tx to Robot1
![IMAGE 2019-06-28 12:47:39](https://user-images.githubusercontent.com/36562673/60333900-ec511800-99a2-11e9-8683-bccf169ff9f9.jpg)
![IMAGE 2019-06-28 12:47:51](https://user-images.githubusercontent.com/36562673/60333910-f3782600-99a2-11e9-9227-9fbd6f655512.jpg)

next step Robot1 tx to energyPovider
![IMAGE 2019-06-28 12:48:42](https://user-images.githubusercontent.com/36562673/60333959-11de2180-99a3-11e9-8071-0cb8360bd369.jpg)
![IMAGE 2019-06-28 12:48:46](https://user-images.githubusercontent.com/36562673/60333965-14407b80-99a3-11e9-9f71-8c7e911d528a.jpg)

**Comment by huhn511** [comment]
Looks really nice!

We could use the same idea to visualize the energy flow. Just flip the dot animation direction and maybe show more dots walking on the line (and maybe we can put an "iota" logo in the token transfer dots and an energy icon (flash) for the energy transfer. 

What do you think?

**Comment by akitablock** [comment]
![Picture1](https://user-images.githubusercontent.com/36562673/60354449-eb38de80-99d4-11e9-9a08-5918ce0ae84c.png)

**Comment by huhn511** [comment]
Gifs:
![2019-06-28_1847502](https://user-images.githubusercontent.com/10562055/60355331-6ba81100-99ce-11e9-8861-0ab3b59ce84e.gif)

![2019-06-28_184552](https://user-images.githubusercontent.com/10562055/60355339-706cc500-99ce-11e9-9144-7f64fbf094c2.gif)
